### ISSUE TITLE
Reference Model Terminology leads to 404

### ISSUE THREAD

**Issue by richardboswell** [cntt-n/CNTT#364]
The link to Reference Model Terminology under section 1.2 in document https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter01.md leads to a 404. The existing link is https://github.com/cntt-n/CNTT/blob/master/ref_model/chapters/glossary.md#1.1, I believe you are trying to link to https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/glossary.md or possibly https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/glossary.md#111-terminology.

**Comment by rabiabdel** [comment]
Thank you @richardboswell will fix.

**Comment by deebhatia** [comment]
@rabiabdel I can pick this up if ok.

**Comment by ulikleber** [comment]
This is already fixed in #595.

**Comment by ulikleber** [comment]
@deebhatia Thanks for the offer, please check the fix.

**Comment by deebhatia** [comment]
@ulikleber Issue still exists. It is an issue in RM Chapter 01. #595 change fixes it for RA2 Chapter 01.

**Comment by ulikleber** [comment]
OK. Got it. Go ahead.
